# Welcome to Jekyll!
#

# Site settings
title: THE COOL KID IS ME
description: 
  Muxuan He <br/>
  Third Year PhD Student in Linguistics @USC
owner: Muxuan He # or company name
first_published: # if migrating another site, the year of your first publish
email: muxuanhe@usc.edu
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://MuxuanHe.github.io" # the base hostname & protocol for your site
social:
  github: https://github.com/MuxuanHe
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: /4Contact.html
  osf: https://osf.io/4wjzq/?view_only=bbf24d6b603a43f482fd0d93f71e89b6
  linkedin-square: https://www.linkedin.com/in/muxuan-he-0048bb293/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
