url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Muxuan He" # the name of your site, e.g. ACME Corp.
description: "4th Year PhD student - University of Southern California"
