url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Darby Grachek" # the name of your site, e.g. ACME Corp.
description: "PhD student - University of Southern California"
