menu:
- {name: 'home', url: ''}
- {name: 'research', url: '/publications'}
# - {name: 'teaching', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

#presentations:
#- {course: 'USC LING 115 (Language and Society)', title: 'Teaching Assistant', dates: 'Aug 2023 - Dec 2023' }
#- {course: 'USC LING 210 (Intro to Linguistics)', title: 'Teaching Assistant', dates: 'Aug 2023 - Dec 2023'}
#- {course: 'MSU LIN 230 (Languages of the World)', title: 'Graduate Instructor', dates: 'June 2020 - August 2020'}



#courses:
#- {course: 'USC LING 115 (Language and Society)', title: 'Teaching Assistant', dates: 'Aug 2023 - Dec 2023' }
#- {course: 'USC LING 210 (Intro to Linguistics)', title: 'Teaching Assistant', dates: 'Aug 2023 - Dec 2023'}
#- {course: 'MSU LIN 230 (Languages of the World)', title: 'Graduate Instructor', dates: 'June 2020 - August 2020'}


social:
- {icon: 'github', link: 'https://github.com/MuxuanHe'}
- {icon: 'linkedin', link: 'www.linkedin.com/in/muxuan-he-0048bb293/'}
- {icon: 'osf', link: 'https://osf.io/yrufk/'}
- {icon: 'google scholar', link: 'https://scholar.google.com/citations?user=9Mm_PL0AAAAJ&hl=en'}


contacts:
- {name: 'Muxuan He', department: 'Department of Linguistics', institution: 'University of Southern California', institution_address: '3601 Watt Way Los Angeles, CA 90089', email: 'muxuanhe[at]usc[dot]edu', office: 'Grace Ford Salvatori Hall 303B'}
