menu:
- {name: 'home', url: ''}
- {name: 'research', url: '/publications'}
# - {name: 'teaching', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}


social:
- {icon: 'github', link: 'https://github.com/MuxuanHe'}
- {icon: 'linkedin', link: 'www.linkedin.com/in/muxuan-he-0048bb293/'}
- {icon: 'website', link: 'https://osf.io/yrufk/'}
- {icon: 'google scholar', link: 'https://scholar.google.com/citations?user=9Mm_PL0AAAAJ&hl=en'}


contacts:
- {institution_address: '3601 Watt Way Los Angeles, CA 90089', email: 'muxuanhe[at]usc[dot]edu', office: 'Department of Linguistics'}
